coverage:
  status:
    project: false
    patch: false

comment: false

ignore:
  - 'examples/**'
  - 'scripts/**'
  - 'vitest.workspace.ts'
  - 'tests/**'
  - 'fixtures/**'
  - 'playwright.config.ts'
  - 'eslint.config.js'
  - '**/tsup.config.ts'
